# Generated by Django 3.2.6 on 2021-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Название (УЗБ)')),
                ('paint_temp_from', models.CharField(blank=True, max_length=10, verbose_name='Температура применения краски ОТ')),
                ('paint_temp_to', models.CharField(blank=True, max_length=10, verbose_name='Температура применения краски ДО')),
                ('usage_temp_from', models.CharField(blank=True, max_length=10, verbose_name='Температура эксплуатации покрытия ОТ')),
                ('usage_temp_to', models.CharField(blank=True, max_length=10, verbose_name='Температура эксплуатации покрытия ДО')),
                ('service_life', models.CharField(blank=True, max_length=10, verbose_name='Срок эксплуатации не менее скольки лет?')),
                ('packaging', models.CharField(blank=True, max_length=40, verbose_name='Об упаковке')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('made_in', models.CharField(blank=True, max_length=100, verbose_name='Страна производителя')),
                ('color_uz', models.CharField(blank=True, max_length=100, verbose_name='Цвет (УЗБ)')),
                ('made_in_uz', models.CharField(blank=True, max_length=100, verbose_name='Страна производителя (УЗБ)')),
                ('fire_resistant_efficiency_group', models.CharField(blank=True, max_length=3, verbose_name='Какая группа огнезащитной эффективности')),
                ('fire_resistant_efficiency_min', models.CharField(blank=True, max_length=3, verbose_name='Сколько минут?')),
                ('reduced_thickness', models.CharField(blank=True, max_length=5, verbose_name='Приведенная толщина металла, мм')),
                ('dry_thickness_paint_layer', models.CharField(blank=True, max_length=8, verbose_name='Толщина сухого слоя краски, мм')),
                ('consumption_paint', models.CharField(blank=True, max_length=8, verbose_name='Теоретический расход краски, кг/м')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
