# Generated by Django 3.2.6 on 2021-08-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consumption_paint',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dry_thickness_paint_layer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fire_resistant_efficiency_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fire_resistant_efficiency_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reduced_thickness',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='TechnicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_resistant_efficiency_group', models.CharField(blank=True, max_length=3, verbose_name='Какая группа огнезащитной эффективности')),
                ('fire_resistant_efficiency_min', models.CharField(blank=True, max_length=3, verbose_name='Сколько минут?')),
                ('reduced_thickness', models.CharField(blank=True, max_length=5, verbose_name='Приведенная толщина металла, мм')),
                ('dry_thickness_paint_layer', models.CharField(blank=True, max_length=8, verbose_name='Толщина сухого слоя краски, мм')),
                ('consumption_paint', models.CharField(blank=True, max_length=8, verbose_name='Теоретический расход краски, кг/м')),
                ('for_product_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.product', verbose_name='Для продукта')),
            ],
        ),
    ]
