# Generated by Django 3.2.6 on 2021-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20210831_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='how_to_save_description',
            field=models.TextField(verbose_name='Условия транспортирования и хранения.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_description',
            field=models.TextField(verbose_name='Особенности применения и эксплуатации'),
        ),
    ]
