# Generated by Django 3.2.6 on 2021-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20210831_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_save_description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Условия транспортирования и хранения.'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Особенности применения и эксплуатации'),
        ),
    ]
