# Generated by Django 3.2.6 on 2021-09-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20210831_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Paint',
        ),
        migrations.AlterModelOptions(
            name='paint',
            options={'verbose_name': 'Краску', 'verbose_name_plural': 'Краски'},
        ),
        migrations.CreateModel(
            name='FlameRetard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Название (УЗБ)')),
                ('temp_usage_from', models.CharField(max_length=8, verbose_name='Температура использования ОТ')),
                ('temp_usage_to', models.CharField(max_length=8, verbose_name='Температура использования ДО')),
                ('usage_without_lost', models.CharField(max_length=20, verbose_name='Расход без учёта потерь (МЛ)')),
                ('packaging', models.CharField(max_length=40, verbose_name='Об упаковке')),
                ('ready_time', models.CharField(max_length=2, verbose_name='Сколько часов сохнет?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Огнезащитную смесь',
                'verbose_name_plural': 'Огнезащитные смеси',
            },
        ),
    ]
