# Generated by Django 3.2.6 on 2021-09-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20210901_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Название (УЗБ)')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Трубу',
                'verbose_name_plural': 'Трубы',
            },
        ),
        migrations.CreateModel(
            name='TechnicTubesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('naming', models.CharField(max_length=20, verbose_name='Наименование')),
                ('diameter', models.CharField(max_length=10, verbose_name='Диаметр (мм)')),
                ('square', models.CharField(max_length=10, verbose_name='Площадь (мм)')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес (кг)')),
                ('for_product_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.tubes', verbose_name='Для продукта')),
            ],
        ),
    ]
