# Generated by Django 3.2.6 on 2021-09-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_technictubesinfo_tubes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technictubesinfo',
            options={'verbose_name': 'Тех Информация', 'verbose_name_plural': 'Тех Информация'},
        ),
        migrations.AlterModelOptions(
            name='tubes',
            options={'verbose_name': 'Трубу или фитинг', 'verbose_name_plural': 'Трубы и фитинги'},
        ),
        migrations.AddField(
            model_name='flameretard',
            name='first_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Первая группа огнезащитной эффективности. \nРасход не менее скольки литров (мл)?'),
        ),
        migrations.AddField(
            model_name='flameretard',
            name='second_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Вторая группа огнезащитной эффективности. \nРасход не менее скольки литров (мл)?'),
        ),
        migrations.AlterField(
            model_name='flameretard',
            name='usage_without_lost',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расход без учёта потерь (МЛ)'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='how_to_save_description',
            field=models.TextField(blank=True, verbose_name='Условия транспортирования и хранения'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='how_to_save_description_uz',
            field=models.TextField(blank=True, verbose_name='Условия транспортирования и хранения (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='article',
            field=models.CharField(blank=True, max_length=10, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='diameter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Диаметр (мм)'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='for_product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tubes', verbose_name='Для продукта'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='naming',
            field=models.CharField(blank=True, max_length=20, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='square',
            field=models.CharField(blank=True, max_length=10, verbose_name='Площадь (мм)'),
        ),
        migrations.AlterField(
            model_name='technictubesinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=10, verbose_name='Вес (кг)'),
        ),
    ]
