# Generated by Django 3.2.6 on 2021-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_auto_20210901_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flameretard',
            name='first_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Первая группа огнезащитной эффективности. Расход не менее скольки литров (мл/м)?'),
        ),
        migrations.AlterField(
            model_name='flameretard',
            name='second_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Вторая группа огнезащитной эффективности. Расход не менее скольки литров (мл\\м)?'),
        ),
    ]
