# Generated by Django 3.2.6 on 2021-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_auto_20210902_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=300, unique=True, verbose_name='URL (Необязательно)'),
        ),
    ]
