# Generated by Django 3.2.6 on 2021-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
    ]
