# Generated by Django 3.2.6 on 2021-09-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
