# Generated by Django 3.2.6 on 2021-09-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=300, verbose_name='URL (Необязательно)'),
        ),
    ]
