# Generated by Django 3.2.6 on 2021-09-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0026_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flameretard',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
        migrations.AddField(
            model_name='paint',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
        migrations.AddField(
            model_name='tubes',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
    ]
