# Generated by Django 3.2.6 on 2021-09-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0027_auto_20210902_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tubes',
            options={'verbose_name': 'Трубу', 'verbose_name_plural': 'Трубы'},
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Название (УЗБ)')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('slug', models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Фитинг',
                'verbose_name_plural': 'Фитинги',
            },
        ),
    ]
