# Generated by Django 3.2.6 on 2021-09-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0031_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicTubesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(blank=True, max_length=20, verbose_name='Наименование')),
                ('diameter', models.CharField(blank=True, max_length=10, verbose_name='Диаметр (мм)')),
                ('square', models.CharField(blank=True, max_length=10, verbose_name='Площадь (мм)')),
                ('weight', models.CharField(blank=True, max_length=10, verbose_name='Вес (кг)')),
                ('for_product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tubes', verbose_name='Для продукта')),
            ],
            options={
                'verbose_name': 'Тех Информация',
                'verbose_name_plural': 'Тех Информация',
            },
        ),
    ]
