# Generated by Django 3.2.6 on 2021-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0032_technictubesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubes',
            name='price',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='tubes',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
    ]
