# Generated by Django 3.2.6 on 2021-08-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_metatags_title_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainbanner',
            old_name='logo',
            new_name='img',
        ),
    ]
