# Generated by Django 3.2.6 on 2021-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_logo_mainbanner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='link',
            field=models.TextField(default='', verbose_name='Ссылка на страницу'),
        ),
    ]
