# Generated by Django 3.2.6 on 2021-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mainbanner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='link',
            field=models.TextField(verbose_name='Ссылка на страницу'),
        ),
    ]
