# Generated by Django 3.2.6 on 2021-08-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210827_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёра', 'verbose_name_plural': 'Партнёры'},
        ),
    ]
