# Generated by Django 3.2.6 on 2021-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_partners_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='subtitle_uz',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок (УЗБ)'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_uz',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (УЗБ)'),
        ),
    ]
