# Generated by Django 3.2.6 on 2021-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210830_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title_uz',
            field=models.CharField(max_length=200, verbose_name='Заголовок (УЗБ)'),
        ),
    ]
