# Generated by Django 3.2.6 on 2021-08-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210830_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
